sba_loan/chat/urls.py
# chat/urls.py
from django.urls import path

from chat.views import Index_View, Room_View


urlpatterns = [
    path("", Index_View.as_view(), name="index"),
    path("<str:room_name>/", Room_View.as_view(), name="room")
]

sba_loan/sba_loan/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sba_website.urls')),
    path('chat/', include('chat.urls')),
]

sba_loan/sba_website/urls.py
from django.urls import path, reverse_lazy
from .views import HomeView,ClientView, NewsView,CreateNewsView,NewsDeleteView,NewsUpdateView, CustomPassWordChangeView
from django.contrib.auth.views import LoginView, LogoutView
from .views import HomeView, DisplayProfileView, CreateUserViews
from .views import DeleteUserView, AccountUpdateView, CreateLoanRequestView, FillLoanRequestView, LoanListViews, PredictLoanView, CompanyUpdateView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('clients_list/', ClientView.as_view(), name='clients_list'),
    path('news_list/', NewsView.as_view(), name='news_list'),
    path('create_news/', CreateNewsView.as_view(), name='create_news'),
    path('signup/', CreateUserViews.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='sba_website/login.html'), name='login'),
    path ("logout/", LogoutView.as_view(), name="logout"),
    path("delete_user/<int:pk>/", DeleteUserView.as_view(), name='delete_user'), 
    path ("<int:pk>/update/", CompanyUpdateView.as_view(), name="company_info_update"),
    path ("<int:pk>/acc_update/", AccountUpdateView.as_view(), name="account_update"),
    path('password_change/', CustomPassWordChangeView.as_view(success_url=reverse_lazy('login')), name='password_change'),
    path ("<int:pk>/news_update/", NewsUpdateView.as_view(), name="news_update"),
    path('profile/', DisplayProfileView.as_view(), name='display_profile'),
    path('loan_list/', LoanListViews.as_view(), name='select_loan_request'),
    path('loan_request/', CreateLoanRequestView.as_view(), name='create_loan_request'),
    path('loan_filling/<int:pk>/', FillLoanRequestView.as_view(), name='fill_loan_request'),
    path('delete_news/<int:pk>/', NewsDeleteView.as_view(), name='delete_news'),
    path('predict_loan/<int:pk>/', PredictLoanView.as_view(), name='predict_loan')
]

sba_loan/sba_website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.core.validators import RegexValidator


class User(AbstractUser):
    """
    Modèle représentant une entreprise avec divers attributs, y compris les informations de contact, 
    la localisation et les détails des employés.

    Attributs :
        company_name (str) : Le nom de l'entreprise.
        phone_number (str) : Le numéro de téléphone de l'entreprise, validé par une expression régulière.
        STATES (list) : Liste des choix représentant les états des États-Unis.
        state (str) : L'état dans lequel se trouve l'entreprise, représenté par un code d'état à 2 lettres.
        NAICS (str) : Le code NAICS (Système de classification des industries de l'Amérique du Nord) de l'entreprise.
        URBAN_RURAL_CHOICES (list) : Liste des choix pour distinguer entre zones urbaines et rurales.
        urbanrural (str) : Indique si l'entreprise se situe dans une zone urbaine ou rurale.
        franchisecode (int) : Un code de franchise unique attribué à l'entreprise.
        role (int) : Le rôle de l'utilisateur associé à l'entreprise (0 pour entreprise, 1 pour conseiller).
        no_emp (int) : Le nombre d'employés travaillant dans l'entreprise.
        username (str) : Le nom d'utilisateur de l'utilisateur associé à l'entreprise.
        email (str) : L'adresse email de l'utilisateur, qui doit être unique.
    """
    
    company_name = models.CharField("Company Name", max_length=250, blank=True)
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',  # Allows optional "+" and 9-15 digits
        message="Phone number must be entered in the format: '+123456789' (9-15 digits)."
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    STATES = [
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('DC', 'District of Columbia'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming')
]

    state = models.CharField(max_length=2, choices = STATES, null=True, default='IN')
    NAICS = models.CharField(max_length=6, blank=True)
    URBAN_RURAL_CHOICES = [
        ('1', 'Urban'),
        ('0', 'Rural'),
    ]
    urbanrural = models.CharField(max_length=1, choices=URBAN_RURAL_CHOICES, null=True, default='0')
    franchisecode = models.PositiveIntegerField(null=True, default='0')
    role = models.IntegerField(null=True, default=0) # 0 = company , 1 = advisor
    no_emp = models.PositiveIntegerField(verbose_name="Number of employees", null=True, default=0)
    username = models.CharField(max_length=100,blank=True)
    USERNAME_FIELD = "email"
    email = models.EmailField(('email address'), unique=True) # changes email to unique and blank to false
    REQUIRED_FIELDS = []

    
class LoanRequest(models.Model):
    """
    Modèle représentant une demande de prêt d'un utilisateur avec diverses informations sur la demande.

    Attributs :
        user_id (ForeignKey) : Clé étrangère pointant vers l'utilisateur qui fait la demande de prêt.
        bank_loan (int) : Montant du prêt bancaire demandé.
        request_date (date) : Date de la demande de prêt, définie automatiquement à la date de création.
        LOW_DOC_CHOICES (list) : Liste des choix pour indiquer si la demande est un prêt à faible documentation.
        lowdoc (str) : Indique si la demande de prêt est à faible documentation (Oui ou Non).
        sba_loan (int) : Montant du prêt SBA (Small Business Administration) demandé.
        revlinecr (str) : Ligne de crédit disponible pour l'entreprise, sous forme de chaîne de caractères.
        term (int) : Durée du prêt en mois.
        reason (str) : Raison de la demande de prêt, sous forme de texte libre.
        status (int) : Statut de la demande de prêt (par exemple, en attente, approuvée, rejetée).
        prediction_result (str) : Résultat de la prédiction associée à la demande de prêt (par défaut "Non prédite").
    """

    user_id = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    bank_loan = models.IntegerField(null=True, default=0)
    request_date = models.DateField(auto_now_add=True)
    LOW_DOC_CHOICES = [
        (True, 'Yes'),
        (False, 'No'),
    ]
    lowdoc = models.BooleanField(max_length=1, choices=LOW_DOC_CHOICES, null=True, default=False)
    sba_loan = models.IntegerField(null=True, default=0)
    revlinecr = models.BooleanField(max_length=50, null=True, default=0)
    term = models.IntegerField(null=True, default=0)
    reason = models.CharField(max_length=500, null=True, default='')
    status = models.IntegerField(null=True, default=0)
    prediction_result = models.CharField(max_length=500, null=True, default='Not predicted')


class News(models.Model):
    """
    Modèle représentant une actualité publiée par un utilisateur.

    Attributs :
        user_id (ForeignKey) : Clé étrangère pointant vers l'utilisateur qui a publié l'actualité.
        title (str) : Le titre de l'actualité.
        topic (str) : Le sujet ou la catégorie de l'actualité.
        date_news (datetime) : La date et l'heure de l'événement lié à l'actualité.
        content (str) : Le contenu détaillé de l'actualité.
        publication_date (datetime) : La date et l'heure de la publication de l'actualité, définie par défaut à la date actuelle.
        news_url (str) : L'URL de l'actualité pour redirection vers la source originale.
    """

    user_id = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, blank=True)
    topic = models.CharField(max_length=250, blank=True)
    date_news = models.DateTimeField(null=True)
    content = models.TextField()
    publication_date = models.DateTimeField(default=timezone.now)
    news_url = models.URLField(max_length=200, blank=True)

sba_loan/sba_website/forms.py
from django import forms 
from .models import News
from django import forms
from sba_website.models import User, LoanRequest
from django.contrib.auth.forms import UserCreationForm
from datetime import date



class CreateNews(forms.ModelForm):
    """
    Formulaire permettant de créer une nouvelle actualité.

    Attributs :
        model (Model) : Le modèle associé à ce formulaire, ici le modèle `News`.
        fields (list) : Liste des champs du modèle à inclure dans le formulaire.
        widgets (dict) : Définition des widgets personnalisés pour certains champs, ici le champ `date_news`
                         qui utilise un champ de saisie de date avec un format spécifique.
    """

    class Meta:
        model = News
        fields = ['topic','date_news','content','news_url', 'publication_date']
        widgets = {'date_news': forms.DateInput(format="%Y-%m-%d", attrs={'type': 'date'})}
        labels = {
            'topic': "Topic",
            'date_news': 'Date of publication',
            'content': 'Content',
            'news_url': 'External url (Optional)',
            'publication_date': 'Current date'
        }

class NewsChangeForm(forms.ModelForm):
    """
    Formulaire permettant de modifier les informations d'une actualité existante.

    Attributs :
        model (Model) : Le modèle associé à ce formulaire, ici le modèle `News`.
        fields (list) : Liste des champs du modèle `News` à inclure dans le formulaire pour la modification. 
                        Ici, il s'agit de `date_news`, `news_url`, `content` et `topic`.
    """
    class Meta:
        model = News
        fields = ['date_news','news_url','content','topic'] 
        labels = {
            'date_news': 'Publication date',
            'news_url': 'External url',
            
        }


class CustomCreationForm(UserCreationForm):
    """
    Formulaire personnalisé pour la création d'un utilisateur avec des informations supplémentaires.

    Attributs :
        model (Model) : Le modèle associé à ce formulaire, ici le modèle `User`.
        fields (list) : Liste des champs du modèle `User` à inclure dans le formulaire pour la création.
                        Ici, il s'agit de `email`, `company_name`, `password1`, `password2`, `NAICS`, 
                        `franchisecode`, `state`, `no_emp`, `urbanrural`, et `phone_number`.
    """

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["email", 'company_name', "password1", "password2", 'NAICS', 'franchisecode', 'state','no_emp', 'urbanrural','phone_number'] #les champs utilisés pour la création d'un profil

class AccountChangeForm(forms.ModelForm):
    """
    Formulaire permettant de modifier les informations d'un utilisateur, telles que l'email et le numéro de téléphone.

    Attributs :
        model (Model) : Le modèle associé à ce formulaire, ici le modèle `User`.
        fields (list) : Liste des champs du modèle `User` à inclure dans le formulaire pour la modification.
                        Ici, il s'agit de `email` et `phone_number`.
    """

    class Meta:
        model = User
        fields = ['email','phone_number'] #les champs mis à jour lors de l'update du profil

class LoanRequestForm(forms.ModelForm):
    """
    Formulaire permettant de soumettre une demande de prêt avec le montant du prêt bancaire et la raison de la demande.

    Attributs :
        model (Model) : Le modèle associé à ce formulaire, ici le modèle `LoanRequest`.
        fields (list) : Liste des champs du modèle `LoanRequest` à inclure dans le formulaire. 
                        Ici, il s'agit de `bank_loan` et `reason`.
    """

    class Meta:
        model = LoanRequest
        fields = ['bank_loan', 'reason'] #les champs mis à jour lors de l'update du profil
        labels= {
            'bank_loan': 'Amount requested ($)',
            'reason': 'Reason for the loan'
        }


class LoanRequestAdvisorForm(forms.ModelForm):
    """
    Formulaire permettant à un conseiller de soumettre des informations supplémentaires pour une demande de prêt.

    Attributs :
        model (Model) : Le modèle associé à ce formulaire, ici le modèle `LoanRequest`.
        fields (list) : Liste des champs du modèle `LoanRequest` à inclure dans le formulaire pour l'avis du conseiller.
                        Ici, il s'agit de `lowdoc`, `sba_loan`, `revlinecr`, et `term`.
    """
    class Meta:
        model = LoanRequest
        fields = ['lowdoc', 'sba_loan', 'term'] #les champs mis à jour lors de l'update du profil
        labels = {
            'lowdoc': 'Low documentation',
            'sba_loan' : 'Amount guaranteed by SBA ($)',
            'term' : 'Loan terms (months)'
        }

class SelectLoanRequest(forms.Form):

    """
    Formulaire permettant de filtrer les demandes de prêt en fonction de différents critères.

    Attributs :
        search_by_company_name (ModelChoiceField) : Champ permettant de rechercher les demandes de prêt par le nom de l'entreprise.
                                                   Il permet de sélectionner un nom d'entreprise parmi ceux enregistrés.
        search_by_amount (IntegerField) : Champ permettant de rechercher les demandes de prêt par montant.
        search_by_status (IntegerField) : Champ permettant de rechercher les demandes de prêt par statut (par exemple, en attente, approuvée, rejetée).
    """
    search_by_company_name = forms.ModelChoiceField(label="Company name", queryset=User.objects.values_list('company_name', flat=True).distinct() , required=False)
    search_by_amount = forms.IntegerField(label="Amount", required=False)
    search_by_status = forms.IntegerField(label="Status", required=False)
    
class CompanyInfoChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['company_name','state', 'NAICS', 'urbanrural', 'no_emp'] #les champs mis à jour lors de l'update du profil

sba_loan/sba_website/templates/sba_website/account_update.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block content %}
<form method="post" class="mb-10 flex flex-col items-center">
  {% csrf_token %}
  <div class="w-full max-w-lg flex flex-col items-start">
      {% for field in form %}
          <div class="mb-4 flex justify-between items-center w-[75%]">
              <label for="{{ field.id_for_label }}" class="primary-color font-bold text-left">
                  {{ field.label }} :
              </label>
              <div class="">
                  {{ field|add_class:"p-2 border border-blue-500 rounded" }}
                  {% for error in field.errors %}
                      <p class="text-red-500 text-sm">{{ error }}</p>
                  {% endfor %}
              </div>
          </div>
      {% endfor %}
  </div>
  <button class="btn mt-4" type="submit">Save</button>
</form>
  <div class="border-t border-black w-[25%] mx-auto"></div>
  <div class="mt-10 mb-10">
    <a href="{% url 'display_profile' %}" class="btn">Cancel</a>
    <a href="{% url 'delete_user' user.id%}" class="btn">Delete my account</a>    
  </div>
{% endblock %}

sba_loan/sba_website/templates/sba_website/clients_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto mt-10">
  <div class="overflow-x-auto">
    <table class="min-w-full border border-primary-color rounded-lg">
      <thead>
        <tr class="bg-gray-100">
          <th class="px-4 py-2 border border-primary-color">ID</th>
          <th class="px-4 py-2 border border-primary-color">Company Name</th>
          <th class="px-4 py-2 border border-primary-color">State</th>
          <th class="px-4 py-2 border border-primary-color">NAICS</th>
          <th class="px-4 py-2 border border-primary-color">Email</th>
          <th class="px-4 py-2 border border-primary-color">Franchise Code</th>
          <th class="px-4 py-2 border border-primary-color">Nb Employees</th>
          <th class="px-4 py-2 border border-primary-color">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for client in clients %}
        <tr>
          <td class="px-4 py-3 border border-primary-color">{{ client.id }}</td>
          <td class="px-4 py-3 border border-primary-color">{{ client.company_name }}</td>
          <td class="px-4 py-3 border border-primary-color">{{ client.state }}</td>
          <td class="px-4 py-3 border border-primary-color">{{ client.NAICS }}</td>
          <td class="px-4 py-3 border border-primary-color">{{ client.email }}</td>
          <td class="px-4 py-3 border border-primary-color">{{ client.franchisecode }}</td>
          <td class="px-4 py-3 border border-primary-color">{{ client.no_emp }}</td>
          <td class="px-4 py-3 border border-primary-color">
            <a href="{% url 'delete_user' client.id %}" class="btn btn-danger mr-2">Supprimer</a>
            <a href="{% url 'company_info_update' client.id %}" class="btn btn-danger">Modifier</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

sba_loan/sba_website/templates/sba_website/company_info_update.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block content %}
<form method="post" class="mb-10 flex flex-col items-center">
  {% csrf_token %}
  <div class="w-full max-w-lg flex flex-col items-start">
      {% for field in form %}
          <div class="mb-4 flex justify-between items-center w-[75%]">
              <label for="{{ field.id_for_label }}" class="primary-color font-bold text-left">
                  {{ field.label }} :
              </label>
              <div class="">
                  {{ field|add_class:"p-2 border border-blue-500 rounded" }}
                  {% if field.help_text %}
                      <p class="text-sm text-gray-500">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="text-red-500 text-sm">{{ error }}</p>
                  {% endfor %}
              </div>
          </div>
      {% endfor %}
  </div>
  <button class="btn mt-4" type="submit">Save</button>
</form>
<div class="border-t border-black w-[25%] mx-auto"></div>
  <div class="mt-10 mb-10">
    <a href="{% url 'display_profile' %}" class="btn">Cancel</a>
  </div>

  
{% endblock %}

sba_loan/sba_website/templates/sba_website/create_news.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="flex flex-col items-center mt-10">
    <div class="min-w-[300px] max-w-sm mt-10 p-4 shadow-md rounded-lg border-t-2 border-green-700 mx-auto">
        <!-- Header Section -->
        <div class="flex justify-center pb-4 border-b">
            <p class="font-bold text-xl primary-color text-center mb-1">Publish an article</p>
        </div>

        <!-- Form Section -->
        <div class="flex flex-col pl-1">
            <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-4">
                        <label for="{{ field.id_for_label }}" class="block font-medium text-gray-700">
                            {{ field.label }}
                        </label>
                        {% if field.name == "content" %}
                            {# For the textarea, add full width and disable manual resize (JS will handle auto-resize) #}
                            {{ field|add_class:"w-full resize-none overflow-hidden" }}
                        {% else %}
                            {{ field|add_class:"w-full" }}
                        {% endif %}
                        {% if field.errors %}
                            <p class="text-red-500 text-sm">{{ field.errors }}</p>
                        {% endif %}
                    </div>
                {% endfor %}
                <input class="btn" type="submit" value="Submit">
            </form>
        </div>

        <!-- Divider Line -->
        <hr class="my-5 border-t border-gray-300">

        <!-- Cancel Button -->
        <ul class="mb-2 flex flex-col items-center gap-5">
            <li><a href="{% url 'display_profile' %}" class="btn">Cancel</a></li>
        </ul>
    </div>
</div>

{# JavaScript to auto-resize any textarea as the user types #}
<script>
document.addEventListener('input', function (event) {
    if (event.target.tagName.toLowerCase() !== 'textarea') return;
    event.target.style.height = 'auto';
    event.target.style.height = event.target.scrollHeight + 'px';
});
</script>
{% endblock content %}

sba_loan/sba_website/templates/sba_website/delete_news.html
{% extends "base.html" %}

{% block content %}
<h2 class="mt-20 text-4xl font-extrabold text-red-700 uppercase text-center">
    Are you sure you want to delete this news?
</h2>
<h3 class="text-2xl font-bold text-red-600 uppercase text-center mt-2">
    This action is not reversible.
</h3>

<form  method='post' class="mt-10">
    {% csrf_token %}
    <button type='submit' class='btn_careful'><i class="fa-solid fa-user-xmark"></i>Yes</button>
    <a href="{% url 'news_list' %}" class="btn">No</a>  
</form>
<br>
{% endblock content %}

sba_loan/sba_website/templates/sba_website/loan_filling.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<div class="container mx-auto mt-10">
  <p class="mb-4 font-bold">Loan n°{{ object.id }}</p>

  <form method="post" action="" class="mb-10 flex flex-col items-center">
    {% csrf_token %}
    <div class="w-full max-w-lg flex flex-col items-start">
      {% for field in form %}
        <div class="mb-4 flex justify-between items-center w-[75%]">
          <label for="{{ field.id_for_label }}" class="primary-color font-bold text-left">
            {{ field.label }} :
          </label>
          <div>
            {{ field|add_class:"p-2 border border-blue-500 rounded" }}
            {% for error in field.errors %}
              <p class="text-red-500 text-sm">{{ error }}</p>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
    <div>
    <button class="btn mt-4" type="submit">Submit</button>
    <button class="btn mt-4"><a href={% url "select_loan_request" %}>Cancel</a></button>
  </form>
</div>
</div>
{% endblock %}

sba_loan/sba_website/templates/sba_website/profile.html
{% extends 'base.html'%}

{% block content %}
<h1 class="text-4xl font-extrabold text-center primary-color mt-8 mb-6">
    Your Profile
</h1>


<div class="flex flex-wrap justify-center items-start gap-10 mt-10 mb-20">
    <div
        class="min-w-[300px] max-w-sm mt-20 p-4 shadow-md rounded-lg border-t-2 border-green-700">
        <div class="flex justify-between pb-4 border-b">
            <p class="font-bold text-xl primary-color">My profile</p>
        </div>
        <ul class="flex flex-col pl-1">
            <li class="border-b py-2 flex justify-between">
                <span class="font-bold primary-color">Company Name :</span>
                <span>{{ user.company_name }}</span>
            </li>
            <li class="border-b py-2 flex justify-between">
                <span class="font-bold primary-color">Email :</span>
                <span>{{ user.email }}</span>
            </li>
            <li class="border-b py-2 flex justify-between">
                <span class="font-bold primary-color">Phone Number :</span>
                <span>{{ user.phone_number }}</span>
            </li>
        </ul>
        <ul class="mt-5 mb-2 flex flex-col items-center gap-5">
            <li><a href="{% url 'account_update' pk=user.pk%}" class="btn">Update my profile</a></li>  
            <li><a href="{% url 'password_change' %}" class="btn">Change password</a></li>       
        </ul>            
    </div>
    <div
    class="min-w-[300px] max-w-sm mt-20 p-4 shadow-md rounded-lg border-t-2 border-green-700">
    <div class="flex justify-between pb-4 border-b">
        <p class="font-bold text-xl primary-color">My Company</p>
    </div>
    <ul class="flex flex-col pl-1">
        <li class="border-b py-2 flex justify-between">
            <span class="font-bold primary-color">State :</span>
            <span>{{ user.get_state_display }}</span>
        </li>
        <li class="border-b py-2 flex justify-between">
            <span class="font-bold primary-color">N° NAICS :</span>
            <span>{{ user.NAICS }}</span>
        </li>
        <li class="border-b py-2 flex justify-between">
            <span class="font-bold primary-color">Franchise :</span>
            {% if user.franchisecode == 0 %}
                <span>None</span>
            {% else %}
                <span>{{ user.franchisecode }}</span>
            {% endif %}
        </li>
        <li class="border-b py-2 flex justify-between">
            <span class="font-bold primary-color">Number of employees :</span>
            <span>{{ user.no_emp }}</span>
        </li>
        <li class="border-b py-2 flex justify-between">
            <span class="font-bold primary-color">Area Type :</span>
            <span>{{ user.get_urbanrural_display }}</span>
        </li>
    </ul>
    <ul class="mt-5 mb-2 flex flex-col items-center gap-5">
        <li><a href="{% url 'company_info_update' pk=user.pk%}" class="btn">Update my company's informations</a></li>
    </ul>  
</div>
    <div
    class="min-w-[300px] max-w-sm mt-20 p-4 shadow-md rounded-lg border-t-2 border-green-700">
    <div class="flex justify-between pb-4 border-b">
        <p class="font-bold text-xl primary-color">Actions</p>
    </div>
    <ul class="flex flex-col pl-1">    
            {% if user.role == 0 %}
            <li class="border-b py-2 flex justify-between">          
                <a href="{% url 'create_loan_request' %}" class="btn">Loan request</a>            
            </li>
            <li class="border-b py-2 flex justify-between">          
                <a href="" class="btn">My loan history</a>            
            </li>
            {% endif %}
            {% if user.role == 1 %}
            <li class="border-b py-2 flex justify-between">
                <a href="{% url 'select_loan_request' %}" class="btn">Loans management</a>
            </li>
            <li class="border-b py-2 flex justify-between">
                <a href="{% url 'clients_list' %}" class="btn">Clients management</a>
            </li>
            <li class="border-b py-2 flex justify-between">
                <a href="{% url 'create_news' %}" class="btn">Write an article</a>
            </li>
            <li class="border-b py-2 flex justify-between">
                <a href="{% url 'news_list' %}" class="btn">Article management</a>
            </li>
            {% endif %}
    </div>
</div>
{% endblock %}